<?php

namespace App\Repository;

use App\Entity\Todo;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * TodoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TodoRepository extends ServiceEntityRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Todo::class);
    }



    public function getSearchParams($number, $name, $category)
    {
         //var_dump($name); die();

        $qb = $this->createQueryBuilder('p')
            ->where('p.name LIKE :name')
            ->andWhere('p.category LIKE :category')
            ->andWhere('p.id LIKE :number')
            ->setParameters(['number'=> '%'.$number .'%','name'=> '%'. $name. '%', 'category' => '%'. $category. '%' ])
            ->getQuery();

            $result = $qb->execute();

        return $result;

    }

}
