#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_lucky_number:
    path: /lucky/number
    controller: App\Controller\LuckyController:number

#blog_list:
#    path: /blog/{page}
#    controller: App\Controller\BlogController:list
todo_list:
    path: /
    controller: App\Controller\TodoController:listAction


todo_meetings:
    path: /meetings/create
    controller: App\Controller\MeetingsController:createMeetings

todo_view_meetings:
    path: /meetings/view
    controller: App\Controller\MeetingsController:viewMeetings